### ISSUE TITLE
Are commune_code right postal/zip codes?

### ISSUE THREAD

**Issue by BeliliFahem** [othmanus/algeria-cities#14]
Does municipality (commune) codes (commune_code) corresponding to real postal/zip codes?
If the "commune" codes which are in the repository are just identifiers for technical purposes, in this case it is better to rename the name of the column "commune_code" in "commune_id" to avoid confusion between technical identifier and commune code (zip code) . 

**Example 1** :  for **El Biar**, the "commune" code (postal code / zip code) that can be found on [the post office site](https://www.poste.dz/customer/bureaux_postaux?wilaya=ALGER+CENTRE) is: 16003. And on the data of this repository we find 580.

**Example 2** : For the "commune"  Béjaia which is located in the Wilaya of Béjaia (the wilaya and the municipality have the same name. Ok.), The postal code is really 06000. But on this deposit, I find 187 as code_commune.

**Comment by othmanus** [comment]
Thanks @BeliliFahem for raising the issue up and for the suggestion.

I confirm that the codes are NOT postal codes. It is a unique identifier for the city. I agree that it should be named differently to avoid confusion, I will update it later.

Spoiler: I am working on adding all the postal codes for each city. Note that a city may have multiple postal codes: sometimes because each neighbourhood has a post office, sometimes because of the villages around the city.

For now, I will close this issue.
